import 'models/Note.dart';

List<Note> list = <Note>[
  Note(1, "Note1", "Allo"),
  Note(2, "Note2", "comment"),
  Note(3, "Note3", "va"),
  Note(4, "Note4", "tu"),
  Note(5, "Note5", "aujourd'hui"),
  Note(6, "Note6", "mon"),
  Note(7, "Note7", "brave"),
  Note(8, "Note8", "j'espère"),
  Note(9, "Note9", "que"),
  Note(10, "Note10", "la"),
  Note(11, "Note11", "vie"),
  Note(12, "Note12", "se"),
  Note(13, "Note13", "passe"),
  Note(14, "Note14", "bien"),
  Note(15, "Note15", "de"),
  Note(16, "Note16", "ton"),
  Note(17, "Note17", "côté"),
  Note(18, "Note18", "car"),
  Note(19, "Note19", "au"),
  Note(20, "Note20", "final"),
  Note(21, "Note21", "c'est"),
];
